// =============================================================================
// TanStack Router instance
// routeTree is auto-generated by `@tanstack/router-plugin` — do not edit.
// =============================================================================

import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  defaultPreloadStaleTime: 0,
});

// Register the router for type safety across the app
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}

