// =============================================================================
// TanStack Router instance
// routeTree is auto-generated by `@tanstack/router-plugin` — do not edit.
// =============================================================================

/*import { createRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

export const router = createRouter({
  routeTree,
  defaultPreload: "intent",
  defaultPreloadStaleTime: 0,
});

// Register the router for type safety across the app
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}*/

import { createRouter as createTanStackRouter } from "@tanstack/react-router";
import { routeTree } from "./routeTree.gen";

//import type { ReactNode } from 'react'
//import { QueryClient } from '@tanstack/react-query'
import { setupRouterSsrQueryIntegration } from "@tanstack/react-router-ssr-query";
import {
  /*TanstackQueryProvider, */ getContext,
} from "./integrations/tanstack-query/root-provider";

export function getRouter() {
  const context = getContext();

  const router = createTanStackRouter({
    routeTree,
    context,
    scrollRestoration: true,
    defaultPreload: "intent",
    defaultPreloadStaleTime: 0,
  });
  //@ts-ignore
  setupRouterSsrQueryIntegration({ router, queryClient: context.queryClient });

  return router;
}

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
